# Generated by Django 5.1.5 on 2025-01-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refreshtoken',
            name='refresh_token',
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='token',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recaptcha',
            name='token',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.TextField(default=''),
        ),
    ]
