# Generated by Django 5.1.5 on 2025-01-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_blacklist_token_alter_recaptcha_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='usuario',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
