# Generated by Django 5.1.5 on 2025-02-07 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_perfilusuario_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blacklist',
        ),
        migrations.RemoveField(
            model_name='refreshtoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='session',
            name='user',
        ),
        migrations.RemoveField(
            model_name='token',
            name='user',
        ),
        migrations.RemoveField(
            model_name='twofactorauth',
            name='user',
        ),
        migrations.DeleteModel(
            name='Recaptcha',
        ),
        migrations.DeleteModel(
            name='RefreshToken',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.DeleteModel(
            name='TwoFactorAuth',
        ),
    ]
